general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    cloudFoundry:
      apiEndpoint: 'https://api.cf.us20.hana.ondemand.com' # default: 'https://api.cf.eu10.hana.ondemand.com'
      org: 'clfqut01'
      space: 'Development'
      credentialsId: 'CloudFoundryCredentails'